### ISSUE TITLE
pydiscourse.exceptions.DiscourseClientError: Payload Too Large

### ISSUE THREAD

**Issue by dkgv** [bennylope/pydiscourse#38]
Hi! I've been trying to get various methods from the library to work to no avail:

```python
from pydiscourse import DiscourseClient
client = DiscourseClient(host='https://forums.mywebsite.com', api_username='username_of_admin', api_key='key')
print(client.users())
```

I get the same exception each time:
```
Traceback (most recent call last):
  File "test_discourse.py", line 3, in <module>
    print(client.users())
  File "C:\Python37\lib\site-packages\pydiscourse\client.py", line 449, in users
    return self._get("/admin/users/list/{0}.json".format(filter), **kwargs)
  File "C:\Python37\lib\site-packages\pydiscourse\client.py", line 1298, in _get
    return self._request(GET, path, params=kwargs, override_request_kwargs=override_request_kwargs)
  File "C:\Python37\lib\site-packages\pydiscourse\client.py", line 1424, in _request
    raise DiscourseClientError(msg, response=response)
pydiscourse.exceptions.DiscourseClientError: Payload Too Large
```

Running `pip freeze | grep discourse` gives me `pydiscourse==1.1.0`. If I access the `/admin/users/list/{0}.json` endpoint directly in my browser I get the expected result, however, what seems to happen through the library is that an error HTML page is returned instead. Any pointers?

**Comment by abkfenris** [comment]
My fix for this (I also caused it...) was merged a few days ago #37 so the next release should solve it.

**Comment by goetzk** [comment]
1.1.0 is our latest release, so should include that fix.

**Comment by dkgv** [comment]
@abkfenris @goetzk that is the version I have installed -- am I missing something or does the issue still persist?

**Comment by abkfenris** [comment]
Yes, #37 (6e319531180f047bb5ed8b42e95c5d6288c1990b) landed a few commits after 1.1.0 (3a4af08827386c2b68d1c5c93e76c736f88c18e9).

**Comment by goetzk** [comment]
@dkgv I've just released v1.1.1 with the bug fix mentioned by @abkfenris included.

**Comment by citadelgrad** [comment]
@goetzk FYI, v1.1.1 is on not pypi, the latest is 1.1.0 is currently available.

**Comment by goetzk** [comment]
@citadelgrad I don't know the magic runes to update pypi.

@bennylope Could you please push 1.1.1 to pypi? it fixes the issue referenced in #38.

Karl.
